Repository Adyen/adyen-java-api-library, pull requests merged in 2023-10, with the labels that each got.

#1137 Fix tests automation/services
  src/test/java/com/adyen/LegalEntityManagementTest.java
  src/test/java/com/adyen/PaymentTest.java
  src/test/java/com/adyen/TransfersTest.java
Labels: Fix

#1143 Update Readme for reintroducing classic platforms API
  README.md
Labels: Documentation

#1147 Add Disputes Api, tests. Adjust Readme and Makefile
  Makefile
  README.md
  src/main/java/com/adyen/model/disputes/AbstractOpenApiSchema.java
  src/main/java/com/adyen/model/disputes/AcceptDisputeRequest.java
  src/main/java/com/adyen/model/disputes/AcceptDisputeResponse.java
  src/main/java/com/adyen/model/disputes/DefendDisputeRequest.java
  src/main/java/com/adyen/model/disputes/DefendDisputeResponse.java
  src/main/java/com/adyen/model/disputes/DefenseDocument.java
  src/main/java/com/adyen/model/disputes/DefenseDocumentType.java
  src/main/java/com/adyen/model/disputes/DefenseReason.java
  src/main/java/com/adyen/model/disputes/DefenseReasonsRequest.java
  src/main/java/com/adyen/model/disputes/DefenseReasonsResponse.java
  src/main/java/com/adyen/model/disputes/DeleteDefenseDocumentRequest.java
  src/main/java/com/adyen/model/disputes/DeleteDefenseDocumentResponse.java
  src/main/java/com/adyen/model/disputes/DisputeServiceResult.java
  src/main/java/com/adyen/model/disputes/DownloadDefenseDocumentRequest.java
  src/main/java/com/adyen/model/disputes/DownloadDefenseDocumentResponse.java
  src/main/java/com/adyen/model/disputes/JSON.java
  src/main/java/com/adyen/model/disputes/ServiceError.java
  src/main/java/com/adyen/model/disputes/SupplyDefenseDocumentRequest.java
  src/main/java/com/adyen/model/disputes/SupplyDefenseDocumentResponse.java
  src/main/java/com/adyen/service/DisputesApi.java
  src/test/java/com/adyen/DisputesTest.java
  src/test/resources/mocks/disputes/post-acceptDispute-accept-dispute-200.json
  src/test/resources/mocks/disputes/post-defendDispute-defend-dispute-200.json
  src/test/resources/mocks/disputes/post-deleteDisputeDefenseDocument-delete-dispute-defense-document-200.json
  src/test/resources/mocks/disputes/post-downloadDisputeDefenseDocument-download-dispute-defense-document-200.json
  src/test/resources/mocks/disputes/post-retrieveApplicableDefenseReasons-retrieve-defense-reasons-200.json
  src/test/resources/mocks/disputes/post-supplyDefenseDocument-supply-defense-document-200.json
Labels: Feature

#1149 Fix the checkout and donations mapping
  Makefile
  src/main/java/com/adyen/model/checkout/BillingAddress.java
  src/main/java/com/adyen/model/checkout/CardDetails.java
  src/main/java/com/adyen/model/checkout/CreateCheckoutSessionRequest.java
  src/main/java/com/adyen/model/checkout/CreateCheckoutSessionResponse.java
  src/main/java/com/adyen/model/checkout/DeliveryAddress.java
  src/main/java/com/adyen/model/checkout/DokuDetails.java
  src/main/java/com/adyen/model/checkout/DonationPaymentMethod.java
  src/main/java/com/adyen/model/checkout/DonationPaymentRequest.java
  src/main/java/com/adyen/model/checkout/PaymentRequest.java
  src/main/java/com/adyen/model/checkout/SubMerchantInfo.java
  src/test/java/com/adyen/CheckoutTest.java
Labels: Breaking change, Don't Merge

#1141 SSLContext PR rebased on develop
  README.md
  src/main/java/com/adyen/Client.java
  src/main/java/com/adyen/Config.java
  src/main/java/com/adyen/httpclient/AdyenHttpClient.java
  src/main/java/com/adyen/httpclient/TerminalLocalAPIHostnameVerifier.java
  src/test/java/com/adyen/ClientTest.java
Labels: Breaking change
